name:                day1
version:             0.1.0.0
github:              "AntoineP77/AdventOfCode2021"
author:              "AntoineP77"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  main-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N


